In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv("run_or_walk.csv")

In [3]:
df.head()

date                time username  wrist  activity  acceleration_x  \
0  2017-6-30  13:51:15:847724020   viktor      0         0          0.2650   
1  2017-6-30  13:51:16:246945023   viktor      0         0          0.6722   
2  2017-6-30  13:51:16:446233987   viktor      0         0          0.4399   
3  2017-6-30  13:51:16:646117985   viktor      0         0          0.3031   
4  2017-6-30  13:51:16:846738994   viktor      0         0          0.4814   

   acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z  
0         -0.7814         -0.0076 -0.0590  0.0325 -2.9296  
1         -1.1233         -0.2344 -0.1757  0.0208  0.1269  
2         -1.4817          0.0722 -0.9105  0.1063 -2.4367  
3         -0.8125          0.0888  0.1199 -0.4099 -2.9336  
4         -0.9312          0.0359  0.0527  0.4379  2.4922

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88588 entries, 0 to 88587
Data columns (total 11 columns):
date              88588 non-null object
time              88588 non-null object
username          88588 non-null object
wrist             88588 non-null int64
activity          88588 non-null int64
acceleration_x    88588 non-null float64
acceleration_y    88588 non-null float64
acceleration_z    88588 non-null float64
gyro_x            88588 non-null float64
gyro_y            88588 non-null float64
gyro_z            88588 non-null float64
dtypes: float64(6), int64(2), object(3)
memory usage: 7.4+ MB


In [5]:
df.isnull().sum()

date              0
time              0
username          0
wrist             0
activity          0
acceleration_x    0
acceleration_y    0
acceleration_z    0
gyro_x            0
gyro_y            0
gyro_z            0
dtype: int64

In [6]:
x=df.iloc[:,5:]
y=df["activity"]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [8]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [9]:
y_pred=nb.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[8740,   82],
       [ 714, 8182]], dtype=int64)

In [11]:
accuracy_score(y_test,y_pred)

0.9550739361101704

In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.99      0.96      8822
           1       0.99      0.92      0.95      8896

    accuracy                           0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



In [13]:
x1=x.iloc[:,0:3]
x2=x.iloc[:,3:]

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x1,y,test_size=0.2)

In [15]:
from sklearn.naive_bayes import GaussianNB
nb1=GaussianNB()
nb1.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [16]:
y_pred=nb1.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_test,y_pred)

array([[8875,   50],
       [ 704, 8089]], dtype=int64)

In [18]:
accuracy_score(y_test,y_pred)

0.9574444068179253

In [19]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96      8925
           1       0.99      0.92      0.96      8793

    accuracy                           0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x2,y,test_size=0.2)

In [21]:
from sklearn.naive_bayes import GaussianNB
nb2=GaussianNB()
nb2.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [22]:
y_pred=nb2.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_test,y_pred)

array([[6571, 2110],
       [4123, 4914]], dtype=int64)

In [24]:
accuracy_score(y_test,y_pred)

0.6482108590134327

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.61      0.76      0.68      8681
           1       0.70      0.54      0.61      9037

    accuracy                           0.65     17718
   macro avg       0.66      0.65      0.65     17718
weighted avg       0.66      0.65      0.64     17718

